name = "semantic-physics"
main = "worker/index.ts"
compatibility_date = "2025-01-01"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[[kv_namespaces]]
binding = "JUDGE_CACHE"
id = "TODO"
preview_id = "TODO"
